global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["host.docker.internal:9464"]
  - job_name: "account-service"
    static_configs:
      - targets: ["host.docker.internal:9465"]
  - job_name: "wallet-service"
    static_configs:
      - targets: ["host.docker.internal:9466"]
  - job_name: "exchange-service"
    static_configs:
      - targets: ["host.docker.internal:9467"]
